"""added description on medial model

Revision ID: 050bfa09c842
Revises: 4d623703f3ea
Create Date: 2025-10-11 14:40:48.345943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050bfa09c842'
down_revision = '4d623703f3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
