"""added featured column in media model

Revision ID: 5986b4beecc9
Revises: d2ac6326bc3c
Create Date: 2025-12-10 13:27:29.491486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5986b4beecc9'
down_revision = 'd2ac6326bc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
