"""new program models

Revision ID: 90de2bcc5f78
Revises: 03d89c07a310
Create Date: 2025-11-28 14:34:05.239806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90de2bcc5f78'
down_revision = '03d89c07a310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('coordinator', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_files')
    op.drop_table('programs')
    # ### end Alembic commands ###
