"""Add member,visotor,HBCs,HBCs attendance models

Revision ID: 974c474147b8
Revises: 050bfa09c842
Create Date: 2025-10-20 15:39:47.932688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974c474147b8'
down_revision = '050bfa09c842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_churches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('residence', sa.String(length=120), nullable=True),
    sa.Column('date_of_visit', sa.Date(), nullable=True),
    sa.Column('prayer_request', sa.Text(), nullable=True),
    sa.Column('follow_up_status', sa.String(length=50), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_church_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_church_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('present_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['home_church_id'], ['home_churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_church_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_church_attendance_date'), ['date'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('residence', sa.String(length=120), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('home_church_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['home_church_id'], ['home_churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    with op.batch_alter_table('home_church_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_church_attendance_date'))

    op.drop_table('home_church_attendance')
    op.drop_table('visitors')
    op.drop_table('home_churches')
    # ### end Alembic commands ###
