"""added residence in new members model

Revision ID: c0e8264dbacf
Revises: 5986b4beecc9
Create Date: 2025-12-18 22:51:36.934719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e8264dbacf'
down_revision = '5986b4beecc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_members', schema=None) as batch_op:
        batch_op.drop_column('residence')

    # ### end Alembic commands ###
