"""add finance fields

Revision ID: cd5bd4de440a
Revises: 90de2bcc5f78
Create Date: 2025-12-03 17:41:15.996636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5bd4de440a'
down_revision = '90de2bcc5f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenditures_date'), ['date'], unique=False)

    with op.batch_alter_table('finance_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_church', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('children_ministry', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.drop_column('source')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('children_ministry')
        batch_op.drop_column('main_church')

    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenditures_date'))

    op.drop_table('expenditures')
    # ### end Alembic commands ###
