"""fix fk constraint name

Revision ID: cdffd8b7604e
Revises: b20fc27c2ba8
Create Date: 2025-10-10 21:29:17.491650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdffd8b7604e'
down_revision = 'b20fc27c2ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_department_id', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_department_id', type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
