"""Restore migrations

Revision ID: ea7c8c81cf61
Revises: cd5bd4de440a
Create Date: 2025-12-05 13:00:41.349243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7c8c81cf61'
down_revision = 'cd5bd4de440a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_missions')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('souls_won', sa.Integer(), nullable=True))
        batch_op.drop_column('support')
        batch_op.drop_column('description')
        batch_op.drop_column('end_date')
        batch_op.drop_column('contact')
        batch_op.drop_column('start_date')
        batch_op.drop_column('partners')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partners', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('support', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('souls_won')
        batch_op.drop_column('location')
        batch_op.drop_column('date')

    op.create_table('_alembic_tmp_missions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('souls_won', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
